### ISSUE TITLE
Swagger será implementado?

### ISSUE THREAD

**Issue by raphaelkieling** [xphub/te-emprego-api#53]
Tenho dúvidas de alguns endpoints necessários caso eu fosse contribuir.

**Comment by danielbonifacio** [comment]
Não. Em andamento, a implementacao baseada em _endpoints_. A documentacao da API sera feita por meio dessa _feature_.

Um exemplo de _endpoint_: https://github.com/te-emprego/api/blob/a45d96ee87a938d35f5d44f0a93560b6f6be753d/src/modules/Users/User.endpoints.ts#L13-L22

A funcao do mesmo eh apontar para o metodo correto e, consequentemente, documentar a API.

A documentacao pode ser acessada diretamente da rota, adicionando um argumento `&docs=true` na _URL_.
